### ISSUE TITLE
Atari 5200 Pac-Man cover

### ISSUE THREAD

**Issue by panzeroceania** [OpenVGDB/OpenVGDB#10]
Pac-Man (USA) [5200] has Ms. Pac-Man (USA) cover
------ Pac-Man -- MD5: f1a4d62d9ba965335fa13354a6264623
------ Ms. Pac-Man -- MD5: ef9a920ffdf592546499738ee911fc1e

**Comment by clobber** [comment]
Fixed in v13 update
