### ISSUE TITLE
Colecovision Donkey Kong cover

### ISSUE THREAD

**Issue by panzeroceania** [OpenVGDB/OpenVGDB#11]
Donkey Kong (USA, Europe) [Colecovision] has Donkey Kong Jr cover
------ Donkey Kong -- MD5: 613a3e457758e274a0e0819ff6aa2d43
------ Donkey Kong Jr -- MD5: 1eb2b9c2d1d113f3860f345a07baeb42

**Comment by clobber** [comment]
Fixed in v13 update
