### ISSUE TITLE
Adventures of Lolo (Japan) incorrect cover

### ISSUE THREAD

**Issue by 0kmg** [OpenVGDB/OpenVGDB#30]
Above game, CRC32 = 297198B9, shows artwork from US version.  This is doubly wrong, since it's both the wrong region and since Adventures of Lolo 1 in Japan was Adventures of Lolo 2 in the US.  This appears to be the correct artwork:
http://www.gamefaqs.com/nes/587074-adventures-of-lolo-2/images/box-3321

Likewise, Adventures of Lolo 2 (Japan) (AoL 3 US), CRC32 = EAB93CFB, is missing artwork which can be found here:
http://www.gamefaqs.com/nes/587075-adventures-of-lolo-3/images/box-80417

**Comment by clobber** [comment]
Great find, thanks! I've corrected this and it'll be available in the next database (auto update) soon.
