### ISSUE TITLE
Shadow Squadron ~ Stellar Assault is coming up with the European cover art (32x)

### ISSUE THREAD

**Issue by 0kmg** [OpenVGDB/OpenVGDB#31]
The rom in question has crc 60C49E4D.  For what it's worth I have my region preference set to Japan, but all other multi-region games that are USA/Europe properly display a US cover.  I dug around in openvgdb.sqlite hoping to find something obvious (like had the image URLs been swapped), but I didn't notice anything wrong (all the links _look_ correct).  Also, I still get the European cover even if I change my region to US.

Weird, no?

**Comment by clobber** [comment]
Shadow Squadron ~ Stellar Assault (USA, Europe).32x is USA/Europe version only.

If you want the Japanese cover art, you'd need the actual Japanese version of the game, Stellar Assault (Japan).32x
