### ISSUE TITLE
Incorrect cover art: Donkey Kong Land (GB)

### ISSUE THREAD

**Issue by zachcoyle** [OpenVGDB/OpenVGDB#32]
Donkey Kong Land has Donkey Kong Land 2's box art

**Comment by clobber** [comment]
Thanks and sorry I missed this. It's fixed for the next db update coming out soon.

I learned that:
- Donkey Kong Land (US/EU) = Super Donkey Kong GB (JP)
- Donkey Kong Land 2 (US/EU) = Donkey Kong Land (JP)
- No "Donkey Kong Land III" version for JP
