### ISSUE TITLE
Wrong Art

### ISSUE THREAD

**Issue by DeFrenZ** [OpenVGDB/OpenVGDB#4]
As requested in #openemu I'm writing down here which art was downloaded wrong with the mac app on a Mac with italian locale. All roms were taken from the no-info romlist:

• GBC/Azure Dreams (USA) (SGB Enhanced) [Extremely low resolution]
• GB/Batman - Return of the Joker (USA, Europe) [Missing Art]
• NES/Castlevania (USA) (Rev A) [Loads Castlevania III]
• GB/Donkey Kong Land (USA, Europe) (SGB Enhanced) [Loads Donkey Kong Land 2]
• NES/Final Fantasy II (USA) (Proto) [Missing Art]
• GBA/Groove Adventure Rave - Hikari to Yami no Daikessen (Japan) [Loads Groove Adventure Rave 2]
• GBA/Mega Man Battle Network 3 - Blue Version (USA) [Missing Art]
• GBA/Mega Man Battle Network 3 - White Version (USA) [Missing Art]
• GBA/Monster Rancher Advance (USA) [Loads Monster Rancher Advance 2]
• GB/Nettou Toushinden (Japan) (Rev A) (SGB Enhanced) [Missing Art]
• GBC/Pokemon - Crystal Version (USA, Europe) (Rev A) [Loads strange but related pic]
• GBA/Pokemon - Leaf Green Version (Europe) (Rev 1) [Loads french version]
• GBA/Recca no Honoo - The Game (Japan) [Missing Art]
• GB/SD Hiryuu no Ken Gaiden (Japan) (SGB Enhanced) [Missing Art]
• GB/SD Hiryuu no Ken Gaiden 2 (Japan) (SGB Enhanced) [Missing Art]
• GBC/Spider-Man (USA, Europe) [Extremely low resolution]
• GBC/Spider-Man 2 - The Sinister Six (USA, Europe) [Missing Art]
• GBC/Tarzan (USA, Europe) [Missing Art]

Hope it helped!

**Comment by clobber** [comment]
Corrected all of these that could be corrected in v13 update
