### ISSUE TITLE
garbage traces of old urls in database

### ISSUE THREAD

**Issue by urherenow** [OpenVGDB/OpenVGDB#40]
You can see them if you look at the database using Notepad++ on Windows, but not in SQLiteStudio (for example). Provenance-emu was picking up those URLs for some reason, and failed to download box art.

Fix is to run vacuum on the database (to clean it up). I ran it using SQLiteStudio, then deleted cached stuff on my iPAD for Provenance, and the issue was resolved.

**Comment by dougmcarthur** [comment]
I'm also having this same issue and can't seem to get box art to download, even on a fresh install of 1.5 beta with a small library of games.

**Comment by clobber** [comment]
1. You all are probably not using the latest version of the database -- this is not my problem.
2. The database *does* get `VACUUM` after a large operation before I upload it.
3. Whether the database has been recently `VACUUM`'d *does not* affect the integrity of the data or SQL queries -- what you are suggesting is complete nonsense.
4. Expect a ban if you absolute idiots continue to spam me with "me toos" from issue https://github.com/Provenance-Emu/Provenance/issues/1314
