### ISSUE TITLE
Compiling Cheat Data based on OpenVGDB romID

### ISSUE THREAD

**Issue by noah978** [OpenVGDB/OpenVGDB#41]
Hello!

First of all, thanks for all the hard work being put into this open source database, the community greatly appreciates it.

I am compiling a SQLite cheat code database which utilizes the romID primary key in the ROMs table as the way for emulator systems to associate a cheat code with a game. So my question is: will the romID (with regards to ROM it's associated with) remain unchanged for the foreseeable future?

Obviously it wouldn't be the end of the world since I could try and write a script to update the cheat database with the changes to romID, but it would be nice to not worry about that.

Thanks!

**Comment by clobber** [comment]
Yes, `romID` would be used as the relationship to `ROMs` -- I don't believe this will change. I have long-term plans for adding cheat codes to the database with the following structure:

```
+----------------------------------------------------------------------+
|                                CHEATS                                |
+=========+=======+===========+============+===========================+
| cheatID | romID | cheatCode | cheatType  | cheatDescription          |
+---------+-------+-----------+------------+---------------------------+
| 1       | 2216  | STAGEO    | Game Genie | All enemies throw hammers |
+---------+-------+-----------+------------+---------------------------+
```

**Comment by noah978** [comment]
Thanks for taking the time to answer!

My current setup looks like this:

| cheatID | romID | cheatName       | cheatDescription | cheatSideEffect | cheatCategoryID | cheatCode    | cheatDeviceID |
|---------|-------|-----------------|------------------|-----------------|-----------------|--------------|---------------|
| 1       | 75511 | Infinite Health |                  |                 | 5               | 620c2b54 ... | 1             |

Where cheatCategoryID is a separate table with categories that help with organizing (Miscellaneous, Infinite, Item Multiplier, etc)

And cheatDeviceID is a separate table with the various cheat systems that the codes belong to (Game Genie, GameShark, Codebreaker, etc)

**Comment by clobber** [comment]
> cheatCategoryID, cheatDeviceID

Nice, those both look good to me.
