### ISSUE TITLE
A common root cause for many cover art problems

### ISSUE THREAD

**Issue by superKoder** [OpenVGDB/OpenVGDB#6]
When there are two (or more) games of which the first game's is complete substring of the second game's name, both will have the second game's cover artwork.

For example, on the Master System, you will see that both 'Wonderboy' (1986) and 'Wonderboy in Monster Land' (1987) show the artwork of the latter.

This is only one of many examples: always when a title is a complete substring of another title.

I have had a look at the SQLite file that is downloaded by OE. These actually show that the paths for the short (aka "substring") titles are wrong by there numbers.

'Wonder Boy' (1986) should have had:
http://image.gamespotcdn.net/gamespot/images/box/1/7/1/588171_85587_front.jpg

But instead got the same one as 'Wonder Boy in Moster Land' (1987) :
http://image.gamespotcdn.net/gamespot/images/box/5/0/0/563500_88161_front.jpg

MY GUESS & PROPOSITION

You are using some kind of flexible lookup (likely based on a regex or something) that is satisfied when it finds all the words. 

However, it should be a little more intelligent than that. It should be aware of other titles with a longer title also matching. 

It could then work by elimination. You keep a list of all the ones that match, and rule out the longer ones, keeping only the shortest. 

I'd be happy to help you out on that one, if you want me to.

**Comment by clobber** [comment]
Hey there, thanks for reporting.

Previously we were doing a 'range search' within some fields due to the way our dataset was structured. We've now rescraped and reformatted our CSVs so that this problem shouldn't happen anymore.

We're going to do a reimport into the database soon.

**Comment by clobber** [comment]
Fixed in v13 update
