### ISSUE TITLE
Incorrect art 

### ISSUE THREAD

**Issue by Science-tastic** [OpenVGDB/OpenVGDB#7]
These might be fixed on the reimport but just so you have it:

Incorrectly loading Japanese box art:
GG: Sonic the hedgehog 
md5: 8a95b36139206a5ba13a38bb626aee25

GG: Sonic & Tails: 
md5 aac8371d2179295159c73ae2cb92892d

Incorrect title in series (this game was mentioned in another issue):
GG: Revenge of Drancon (NA name for Wonderboy on GG): Showing artwork for "Wonderboy: The Dragon's trap"
md5: 03adbea26158137de3f18d82e119c520

Incorrect art:
NES: Kung Fu is showing artwork for "Jackie Chan's Action Kung Fu" 
md5: 27e5c62c6c169896bf80bafb6595ceb8

**Comment by clobber** [comment]
Fixed in v13 update
