### ISSUE TITLE
Wrong Art #2

### ISSUE THREAD

**Issue by DeFrenZ** [OpenVGDB/OpenVGDB#8]
Other wrong arts, still from no-intro:

• ColecoVision/Alcazar: The Forgotten Fortress [Cropped Art]
• ColecoVision/BurgerTime [Missing Art]
• ColecoVision/Mr. Do! [Loads Mr. Do!'s Castle]
• ColecoVision/Slither [Missing Art]
• ColecoVision/Tomarc the Barbarian [Missing Art]
• Game Gear/Shining Force II: The Sword of Hajya [Missing Art]
• Game Gear/Shinobi [Loads Shinobi II]
• Nintendo64/Bakuretsu Muteki Bangaioh [Missing Art]
• Nintendo64/Quake 64 [Missing Art]
• Sega Master System/Fantasy Zone II: The Tears of Opa-Opa [Missing Art]
• Sega Mega Drive/Captain Planet and the Planeteers [Missing Art]
• Sega Mega Drive/The Chaos Engine 2 [Missing Art]
• Sega Mega Drive/Dahna Megami Tanjou [Missing Art]
• Sega Mega Drive/Hit the Ice: VHL: The Official Video Hockey League [Missing Art]
• Sega Mega Drive/Jim Power: The Arcade Game [Missing Art]
• Sega Mega Drive/Monster World IV (USA, Europe) (En,Ja) (Virtual Console) [Missing Art]
• Sega Mega Drive/NHL '94 [Missing Art]
• Sega Mega Drive/Yu Yu Hakusho: Makyou Toitsusen [Missing Art]

**Comment by clobber** [comment]
Corrected all of these that could be corrected in v13 update
